feat: accelerate SNARK verification
filecoin-project/rust-fil-proofs pull request #1271
Opened 2020-09-02 16:26 UTC by vmx

This PR integrates lotus-blst in order to accelerate the SNARK verification.

This feature can be enabled with the `use_lotus_blst` setting.

2020-09-02 16:55 UTC, vmx commented
The CI feature is real :(

```
Caused by:
  process didn't exit successfully: `rustc --crate-name api --edition=2018 filecoin-proofs/tests/api.rs --error-format=json --json=diagnostic-rendered-ansi --emit=dep-info,link -C debuginfo=2 --test --cfg 'feature="default"' --cfg 'feature="gpu"' -C metadata=fdd96be771c9b4c8 -C extra-filename=-fdd96be771c9b4c8 --out-dir /mnt/crate/target/debug/deps -C incremental=/mnt/crate/target/debug/incremental -L dependency=/mnt/crate/target/debug/deps --extern anyhow=/mnt/crate/target/debug/deps/libanyhow-bb1f22840603914d.rlib --extern bellperson=/mnt/crate/target/debug/deps/libbellperson-031e3e345f017bf7.rlib --extern bincode=/mnt/crate/target/debug/deps/libbincode-cc2344130d624174.rlib --extern bitintr=/mnt/crate/target/debug/deps/libbitintr-04137a5dd95121f3.rlib --extern bitvec=/mnt/crate/target/debug/deps/libbitvec-81813eca7ef3e303.rlib --extern blake2b_simd=/mnt/crate/target/debug/deps/libblake2b_simd-c07fee3d8c337a20.rlib --extern blake2s_simd=/mnt/crate/target/debug/deps/libblake2s_simd-7bafbc55315bfdc8.rlib --extern byteorder=/mnt/crate/target/debug/deps/libbyteorder-0128a5c530927307.rlib --extern chrono=/mnt/crate/target/debug/deps/libchrono-7f1222cef5adeb76.rlib --extern clap=/mnt/crate/target/debug/deps/libclap-866fd5b3a922ba60.rlib --extern criterion=/mnt/crate/target/debug/deps/libcriterion-e993bf9ff540b96b.rlib --extern dialoguer=/mnt/crate/target/debug/deps/libdialoguer-cef12765c55c8219.rlib --extern env_proxy=/mnt/crate/target/debug/deps/libenv_proxy-e812efe3bb8c5ee9.rlib --extern failure=/mnt/crate/target/debug/deps/libfailure-9d41501bcd822c0d.rlib --extern ff=/mnt/crate/target/debug/deps/libfff-f56442409db2e1ef.rlib --extern fil_sapling_crypto=/mnt/crate/target/debug/deps/libfil_sapling_crypto-aa6d0ec8344f3382.rlib --extern fil_logger=/mnt/crate/target/debug/deps/libfil_logger-27fe9915c903410d.rlib --extern filecoin_proofs=/mnt/crate/target/debug/deps/libfilecoin_proofs-e60825aeb6e600cc.rlib --extern flate2=/mnt/crate/target/debug/deps/libflate2-8ec6e7f123f14e72.rlib --extern generic_array=/mnt/crate/target/debug/deps/libgeneric_array-470449e0d8b8a854.rlib --extern groupy=/mnt/crate/target/debug/deps/libgroupy-fc2ca362e0bdbf51.rlib --extern hex=/mnt/crate/target/debug/deps/libhex-e94640a35d861ddf.rlib --extern humansize=/mnt/crate/target/debug/deps/libhumansize-69db479e032f50e3.rlib --extern indicatif=/mnt/crate/target/debug/deps/libindicatif-7bc8985c83603314.rlib --extern itertools=/mnt/crate/target/debug/deps/libitertools-caead37338afae75.rlib --extern lazy_static=/mnt/crate/target/debug/deps/liblazy_static-6c121bb41812eb8d.rlib --extern log=/mnt/crate/target/debug/deps/liblog-47f7c564d7739ca0.rlib --extern memmap=/mnt/crate/target/debug/deps/libmemmap-23f617c884b63556.rlib --extern merkletree=/mnt/crate/target/debug/deps/libmerkletree-364eb1a34c79d498.rlib --extern paired=/mnt/crate/target/debug/deps/libpaired-c8fbead9f589ed13.rlib --extern pbr=/mnt/crate/target/debug/deps/libpbr-e78bd3bebdeed296.rlib --extern phase2=/mnt/crate/target/debug/deps/libphase21-72c92feeb3e96887.rlib --extern pretty_assertions=/mnt/crate/target/debug/deps/libpretty_assertions-3eaa815b7340ba50.rlib --extern rand=/mnt/crate/target/debug/deps/librand-55993dcb6757b051.rlib --extern rand_chacha=/mnt/crate/target/debug/deps/librand_chacha-692f681537657170.rlib --extern rand_xorshift=/mnt/crate/target/debug/deps/librand_xorshift-43202c9406adb08e.rlib --extern rayon=/mnt/crate/target/debug/deps/librayon-ead13ed46c4d75eb.rlib --extern regex=/mnt/crate/target/debug/deps/libregex-99716d94bab63cb4.rlib --extern reqwest=/mnt/crate/target/debug/deps/libreqwest-f1dd35a9d199e032.rlib --extern rexpect=/mnt/crate/target/debug/deps/librexpect-4a373b2aff764158.rlib --extern serde=/mnt/crate/target/debug/deps/libserde-2373d6f82fe839e2.rlib --extern serde_json=/mnt/crate/target/debug/deps/libserde_json-0b44ba9722152433.rlib --extern sha2=/mnt/crate/target/debug/deps/libsha2-9c71bf9c68bcdb79.rlib --extern simplelog=/mnt/crate/target/debug/deps/libsimplelog-728c858e9b9c0849.rlib --extern storage_proofs=/mnt/crate/target/debug/deps/libstorage_proofs-faf6cf2952d781fe.rlib --extern structopt=/mnt/crate/target/debug/deps/libstructopt-9c82243dc21e9b11.rlib --extern tar=/mnt/crate/target/debug/deps/libtar-57e00cd9f29b32a7.rlib --extern tempfile=/mnt/crate/target/debug/deps/libtempfile-6b0b337a417ad9c4.rlib --extern typenum=/mnt/crate/target/debug/deps/libtypenum-de906ead2317e9e4.rlib -C link-dead-code -L native=/mnt/crate/target/debug/build/fff-15798b1749793e13/out -L native=/mnt/crate/target/debug/build/fil-sapling-crypto-1da2a98832d8e3d2/out -L native=/mnt/crate/target/debug/build/openssl-sys-67e465c5a4b1c714/out/openssl-build/install/lib -L native=/mnt/crate/target/debug/build/lotus_blst-5d86f1f60aa1bf1d/out -L native=/mnt/crate/target/debug/build/lotus_blst-5d86f1f60aa1bf1d/out -L native=/mnt/crate/target/debug/build/neptune-triton-761939ce8c98138f/out -L native=/mnt/crate/target/debug/build/sha2-asm-49a87f29ee0ff245/out -L native=/mnt/crate/target/debug/build/sha2-asm-49a87f29ee0ff245/out` (exit code: 1)
warning: build failed, waiting for other jobs to finish...
error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-L" "/****/.rustup/toolchains/1.43.1-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "/mnt/crate/target/debug/deps/benchy-86fcfd16bffbfafc.101q1aiqd5f2164p.rcgu.o" "/mnt/crate/target/debug/deps/benchy-86fcfd16bffbfafc.10383h9r8ftn47oz.rcgu.o" "/mnt/crate/target/debug/deps/benchy-86fcfd16bffbfafc.108eoww0pbdoqma2.rcgu.o" "/mnt/crate/target/debug/deps/benchy-86fcfd16bffbfafc.10fn4nfltpyllr7t.rcgu.o" "/mnt/crate/target/debug/deps/benchy-86fcfd16bffbfafc.10r9sjz85ivxh82i.rcgu.o" "/mnt/crate/target/debug/deps/benchy-86fcfd16bffbfafc.10x4riqlgfdhgsb0.rcgu.o" "/mnt/crate/target/debug/deps/benchy-86fcfd16bffbfafc.10z2g7mwhj2vc9n5.rcgu.o" "/mnt/crate/target/debug/deps/benchy-86fcfd16bffbfafc.11enm346jamsimip.rcgu.o" "/mnt/crate/target/debug/deps/benchy-86fcfd16bffbfafc.11wiw2bi83saub3q.rcgu.o" "/mnt/crate/target/debug/deps/benchy-86fcfd16bffbfafc.124s96yqwdgrdemm.rcgu.o" "/mnt/crate/target/debug/deps/benchy-86fcfd16bffbfafc.12c4ipg29t01fge9.rcgu.o" "/mnt/crate/target/debug/deps/benchy-86fcfd16bffbfafc.130yawj54hvy29yp.rcgu.o" "/mnt/crate/target/debug/deps/benchy-86fcfd16bffbfafc.131piwg0ckecsvp6.rcgu.o" "/mnt/crate/target/debug/deps/benchy-86fcfd16bffbfafc.134id6g1gt1mzaoa.rcgu.o" "/mnt/crate/target/debug/deps/benchy-86fcfd16bffbfafc.136yf7h0zd4ruy2g.rcgu.o" "/mnt/crate/target/debug/deps/benchy-86fcfd16bffbfafc.13pfg07wg7kaaiyv.rcgu.o" "/mnt/crate/target/debug/deps/benchy-86fcfd16bffbfafc.13pthzlzrzia2mq3.rcgu.o" "/mnt/crate/target/debug/deps/benchy-86fcfd16bffbfafc.13sdqrf29dpq85oi.rcgu.o" "/mnt/crate/target/debug/deps/benchy-86fcfd16bffbfafc.13trsy6l6ucf704t.rcgu.o" "/mnt/crate/target/debug/deps/benchy-86fcfd16bffbfafc.141untu2m6y22ahl.rcgu.o" "/mnt/crate/target/debug/deps/benchy-86fcfd16bffbfafc.1473mnpz8q0qsqux.rcgu.o" "/mnt/crate/target/debug/deps/benchy-86fcfd16bffbfafc.14n0kp79arjr2s5y.rcgu.o" "/mnt/crate/target/debug/deps/benchy-86fcfd16bffbfafc.14p8pf4b65bkr1o.rcgu.o" "/mnt/crate/target/debug/deps/benchy-86fcfd16bffbfafc.14q6metblbg2ethc.rcgu.o" "/mnt/crate/target/debug/deps/benchy-86fcfd16bffbfafc.14sxkzwrf911hs1h.rcgu.o" "/mnt/crate/target/debug/deps/benchy-86fcfd16bffbfafc.15b8pt7pfl1cei2h.rcgu.o" "/mnt/crate/target/debug/deps/benchy-86fcfd16bffbfafc.15s2aqa8zb85prko.rcgu.o" "/mnt/crate/target/debug/deps/benchy-86fcfd16bffbfafc.15ykwhkzrwj88nxf.rcgu.o" "/mnt/crate/target/debug/deps/benchy-86fcfd16bffbfafc.162uyljcaw4h71qr.rcgu.o" "/mnt/crate/target/debug/deps/benchy-86fcfd16bffbfafc.16qfyya5mq5ivyru.rcgu.o" "/mnt/crate/target/debug/deps/benchy-86fcfd16bffbfafc.17n1noqlhn0fugj9.rcgu.o" "/mnt/crate/target/debug/deps/benchy-86fcfd16bffbfafc.18xhmxn5r5mlpxch.rcgu.o" "/mnt/crate/target/debug/deps/benchy-86fcfd16bffbfafc.196bs6jw7qy4msaa.rcgu.o" "/mnt/crate/tar [...]

2020-09-02 22:25 UTC, vmx commented
We are down to a build failure on OSX. I can't help with that one, I'm on Linux.

2020-09-03 19:35 UTC, porcuquine approved these changes
Looks good. Let's just get the crate published so we don't merge a git dependency.

2020-09-03 20:19 UTC, porcuquine requested changes
README should be updated to document `use_lotus_blst`, and that setting should be changed based on the new repo name (`fil-blst`).

2020-09-03 22:00 UTC, porcuquine approved these changes
Looks good (again).

2020-09-03 22:34 UTC, merged

2020-09-12 17:27 UTC, porcuquine commented
> README should be updated to document use_lotus_blst, and that setting should be changed based on the new repo name (fil-blst).

@vmx It looks like this didn't actually happen. (I thought for some reason it had — sorry for premature approval. Let's do this in a follow-up. I'm sad it didn't make it in the corresponding release and communicate directly the need to set `FIL_PROOFS_USE_FIL_BLST=1` to realize these gains.)