refactor: move storage-proofs fr32.rs into its own crate
filecoin-project/rust-fil-proofs pull request #1387
Opened 2020-12-04 18:15 UTC by DrPeterVanNostrand

Moves `storage-proofs::fr32` into it's own crate. 

Issue #1343

2020-12-07 14:52 UTC, dignifiedquire commented
There are more things in filecoin-proofs `fr32.rs` and `fr32_reader.rs`, can you pull those in too please?

2020-12-07 15:28 UTC, DrPeterVanNostrand commented
@dignifiedquire yup, np

2020-12-09 18:15 UTC, dignifiedquire commented on fr32/Cargo.toml
> +pairing = ["bellperson/pairing"]
needs a `gpu` feature, enabling `bellperson/gpu`

2020-12-09 18:17 UTC, dignifiedquire requested changes
please enable ci for the new crate

2020-12-10 13:57 UTC, cryptonemo commented
@DrPeterVanNostrand When you rebase and push, the CI should complete as expected (at least the phase2 related jobs that don't exist any longer won't be required)

2020-12-11 14:30 UTC, dignifiedquire requested changes
almost, just some cargo feature updates missing

2020-12-11 14:30 UTC, dignifiedquire commented on storage-proofs/post/Cargo.toml
>  gpu = ["storage-proofs-core/gpu", "filecoin-hashers/gpu"]
this and the other crates depending on `fr32` will now need to enable the `gpu` feature

2020-12-14 13:52 UTC, dignifiedquire approved these changes

2020-12-14 13:52 UTC, merged