Feat/neptune opencl
filecoin-project/rust-fil-proofs pull request #1397
Opened 2021-01-21 20:38 UTC by porcuquine

2021-01-21 23:36 UTC, dignifiedquire commented on filecoin-hashers/Cargo.toml
> +default = ["gpu2", "pairing", "blake2s", "poseidon", "sha256"]
revert

2021-01-21 23:37 UTC, dignifiedquire commented on filecoin-proofs/Cargo.toml
> +default = ["gpu2", "pairing"]
revert

2021-01-21 23:37 UTC, dignifiedquire commented on storage-proofs-core/Cargo.toml
> +default = ["gpu2", "pairing"]
revert

2021-01-21 23:37 UTC, dignifiedquire commented on storage-proofs-porep/Cargo.toml
> +default = ["pairing", "gpu2"]
revert

2021-02-12 13:36 UTC, dignifiedquire commented
@cryptonemo @porcuquine what's the status of this?

2021-02-12 13:42 UTC, cryptonemo commented
> @cryptonemo @porcuquine what's the status of this?

I haven't tested it, but the changes are mostly feature related, so it depends entirely on the state of neptune's usage of them.  Can revisit after other issues are fixed.

2021-02-12 18:48 UTC, porcuquine commented
This fully integrates the neptune OpenCL changes. It does not realize the full expected performance gains because we now hit a bottleneck in how the data is loaded onto the GPU from disk.

As @dignifiedquire and I discussed, the likely next step is to release this so users can test to ensure they are able to use the `gpu2` flag without problems. Once we establish that, we can remove `gpu2` and default to using neptune's `opencl` flag as the default (when `gpu`) is specified. This will keep the code simpler and could be accomplished when the further optimization to the code here is complete.

If it takes too long, or I have extra time, I can perform the optimization first — but the above is a logical progression and what we have discussed as the plan of record. I haven't had time to actually investigate the fix, but some discussion has prompted my memory, and I think I know the general shape of the problem.

2021-02-15 13:46 UTC, cryptonemo requested changes
Looks good, will merge after a rebase

2021-02-16 19:56 UTC, porcuquine commented
This is rebased now.

2021-02-16 20:20 UTC, cryptonemo approved these changes
Looks good -- clear to merge (squash and merge, preferred) when CI is happy.

2021-02-16 22:38 UTC, merged